apiVersion: v1
data:
  accounts.deploy: apiKey
  repositories: |
  {{- toYaml .Values.argocd.repositories | nindent 4 }}
  repository.credentials: |
    - url: {{ .Values.argocd.repositoryCredentials }}
      sshPrivateKeySecret:
        key: ssh-privatekey
        name: github-ssh-key
      type: git
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - PipelineRun
      - TaskRun
  resource.customizations: |
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
