---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-ssh-key
spec:
  backendType: vault
  vaultMountPoint: {{ .Values.vault.auth_path }}
  vaultRole: {{ .Values.vault.role_name }}
  data:
  - name: ssh-privatekey
    key: {{ .Values.argocd.externalSecret.githubSshKey.key }}
    property: {{ .Values.argocd.externalSecret.githubSshKey.property }}
  template:
    type: kubernetes.io/ssh-auth
